### PR TITLE
add Bigstringaf_unix

### PR DESCRIPTION
**Pull request by madroach**
Implementing reads and writes from/to unix filedescriptors / sockets.

* does _not_ depend on bigstringaf
  * should it rather be a separate project?
  * is the naming sensible? maybe better name it ``bigstring-io``?
  * Im just curious, what does the _af_ in bigstringaf stand for?
* Still not tested on Windows
* what about js? can this be implemented for js, too? should it?

### CODE REVIEW

**Comment by seliopou** [comment]
I started reviewing this and then realized that it doesn't actually depend on `bigstringaf` at all. I suppose you could just create a new project and just call it `bigstring-unix` in that case. How do you feel about that?

**Comment by madroach** [comment]
That's what I already said in the PR-message:
>     * does _not_ depend on bigstringaf
>       
>       * should it rather be a separate project?
>       * is the naming sensible? maybe better name it `bigstring-io`?
>       * Im just curious, what does the _af_ in bigstringaf stand for?

I avoided dependencies on bigstringaf on purpose, but I thought it might be better to add it to an existing project rather than publish it independently. But if you think it would be best to publish it separately, I could do that, too. What's your experience / opinion?

**Comment by seliopou** [comment]
I'd prefer independent, since this doesn't use `bigstringaf`. I don't think I'd add much outside of the comments I've already provided, and it'll be easier to maintain for you without having to go through a third-party's repository. (I also maintain plenty of libraries as-is, I'm not enthusiastic about adding another one to the mix.)

**Comment by madroach** [comment]
Thanks!

**Pull request closed without merging**
