### PR TITLE
update for jsoo#883

### PR DESCRIPTION
**Pull request by hhugo**
Update the js_of_ocaml runtime and use the newly added bigarray blit functions.

- [x] wait for https://github.com/ocsigen/js_of_ocaml/pull/883 to be merge
- [x] wait for an officially release https://github.com/ocaml/opam-repository/pull/15253

### CODE REVIEW

**Comment by hhugo** [comment]
Jsoo has been released.  Release/Review this whenever you have time.

**Comment by hhugo** [comment]
Gentle ping

**Comment by rgrinberg** [comment]
Thanks Hugo. The PR looks good.

**Comment by seliopou** [comment]
I'm not quite sure the right way to constraint the JSOO version in the OPAM file. Any guidance on that @hhugo? Use `conflicts`?

**Comment by hhugo** [comment]
`conflicts` looks appropriate

**Pull request merged**
