### PR TITLE
Freestanding support (on top of #12)

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Comment by seliopou** [comment]
Tested?

**Comment by hannesm** [comment]
this is ugly: xen and freestanding are now built and installed in the respective subdirectories (both bigstringaf.ml/i and the C stubs):
- since `ld` when passed the `-l filespec` flag searches for `libfilespec.a` (for static linking, the only mode of linking we're interested in mirage), but the `libbigstringaf_freestanding_stubs.a` is installed within `OPAM_ROOT/lib/bigstringaf/freestanding/`, I changed it to use `:freestanding/libbigstringaf_freestanding_stubs.a` (another approach is to extend the mirage command line utility to know about bigstringaf and drag in bigstringaf.freestanding / .xen for these targets -- in a similar vain as io-page, maybe by introducing new packages bigstringaf-xen and bigstringaf-freestanding -- issue here is that it requires modifications to mirage as well)
- `META.bigstring.template` was not picked up by jbuilder and was missing the `# JBUILDER_GEN`
- in `freestanding` subdirectory, I have to depend on `mirage-solo5` since `ocaml-freestanding does not install a `META` file and thus is never considered to be installed by `jbuilder` -- but `pkg-config` uses `ocaml-freestanding` to gather the C flags
- I translated parts of lib_test into a unikernel at https://gist.github.com/hannesm/7cc20fa945c461e3488227b6cb7ed9c9 which builds and executes fine and manual comparison in its output shows that it actually works

**Comment by hannesm** [comment]
@seliopou the freestanding part I tested on my laptop, I don't have access to xen machines, so no testing of that code base...

**Comment by hannesm** [comment]
a solution to the second bullet point would be if someone with more knowledge of jbuilder manages to (a) only built the copied .c file and (b) install this into the top-level directory instead of a subdirectory.

**Comment by seliopou** [comment]
Sorry if these are stupid questions but I'm not too familiar with the freestanding project, nor the intricacies of Mirage linking. If somebody wants to just use this library on a UNIX-like system, what do have have to do and what gets built? Do they just specify `bigstringaf` as a jbuild and OPAM dependency? Would that just build `bigstringaf` once?

Now if somebody wants to build this as part of a Mirage project, what do they do? Is it sufficient to again just specify `bigstringaf` as a jbuild and OPAM dependency? Or do they have to specify `bigstringaf.xen` as a jbuild dependency? In that case, does the library get built twice?

I don't get the freestanding issue enough to even ask a question about it. So I just trust that your test is evidence enough that it works.

**Comment by dinosaure** [comment]
I'm interesting about a solution too when I switched [`checkseum`](https://github.com/dinosaure/checkseum.git) on `jbuilder` too.

**Comment by seliopou** [comment]
@hannesm Could you clarify how one would use these different subpackages, or point me to some documentation that explains how?

**Comment by hannesm** [comment]
sorry, I missed your earlier question.

I'll elaborate on what is needed for MirageOS support (this is the current state - we hope to clean this up once opam2 is released):
- all the C code needs to be compiled with a different set of CFLAGS (namely `-mno-red-zone` since we're executing in ring0), includes and LDFLAGS.  The full set of flags is provided by mirage-xen/ocaml-freestanding via `pkg-config` (see `pkg-config --static mirage-xen-posix --cflags`) - in this PR done by `cflags.sh`)
- this C code needs to be linked into a static archive (e.g. `libbigstringaf_xen_stubs.a`)
- this archive is added via `META.in` as tag `xen_linkopts` to the `META` file
- the `mirage` utility picks the target-specific `.._linkopts` up in the linker step which produces the statically linked binary (also called unikernel) in https://github.com/mirage/mirage/blob/3.1.0/lib/mirage.ml#L1924 - which uses `ocamlbuild` / `ocamlfind` for this task
- due to technical debts (and to keep xen and solo5 coinstallable (not sure whether this is worth it)), we're in the situation where the solo5 (i.e. KVM/BHyve/VMM) target and the xen target have some disjoint code paths, and we need the above for both `xen_...` and `freestanding_...` with slightly different flags
 
Now, this PR adds more than the above needed to bigstringaf - I'm sorry for that.  The reason behind introducing subpackages (`bigstringaf.xen` and `bigstringaf.freestanding`) which are not supposed to be used by anyone is that I/we so far weren't able to find another way to let jbuilder/dune compile only the above mentioned C archive with the custom linker flags _if and only if_ mirage-xen-posix/ocaml-freestanding is installed via opam.  The OCaml code (and subpackages) don't need to be built multiple times, it's only about the C archives -- to be built as an optional dependency if mirage-xen-posix/ocaml-freestanding is installed in the opam switch.

Users of bigstringaf only ever need to depend on bigstringaf.

**Comment by seliopou** [comment]
Thanks for the explanation!

**Pull request merged**
